# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e558830c9cccd882006dc4f35d6245baf5951c884e0b503680ddcd6d2f963ad8ce988efe0218f0db0103b3fe878c6bf941edf088fb33036b8834c6581a7fb7

test:
  secret_key_base: fe104f8bbb0f2a434a6402fcd61f652b7be1158b92c4edde4ea7a16241c0adc024fd7e31408f15e3b32e6e393bcae88449383d59cdfe6571013216ad621a1ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
